# logging settings
logging:
  level:
    root: info
    org:
      apache: warn
      hibernate: warn
      springframework: warn

  pattern:
    # special characters need to be escaped / quoted
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%thread) %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'

# indent the returned JSON responses
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:test
    username: sa
    password: aVeryComplexPassword
