# the name of the current app
spring:
  application:
    name: spring-boot-dev-tools-demo

  # indent the returned JSON responses
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: aVeryComplexPassword

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

    open-in-view: false

# logging settings
logging:
  level:
    root: info
    com:
      zaxxer: warn
    org:
      apache: warn
      springframework: warn
      hibernate: warn

  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'
